package Strore.entity;
// Generated Aug 25, 2019 7:33:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Attributevalue generated by hbm2java
 */
public class Attributevalue  implements java.io.Serializable {


     private Integer id;
     private Attribute attribute;
     private String name;
     private Set productses = new HashSet(0);

    public Attributevalue() {
    }

	
    public Attributevalue(Attribute attribute, String name) {
        this.attribute = attribute;
        this.name = name;
    }
    public Attributevalue(Attribute attribute, String name, Set productses) {
       this.attribute = attribute;
       this.name = name;
       this.productses = productses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Attribute getAttribute() {
        return this.attribute;
    }
    
    public void setAttribute(Attribute attribute) {
        this.attribute = attribute;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }




}


