package Strore.entity;
// Generated Aug 25, 2019 7:33:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Attribute generated by hbm2java
 */
public class Attribute  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set attributevalues = new HashSet(0);

    public Attribute() {
    }

	
    public Attribute(String name) {
        this.name = name;
    }
    public Attribute(String name, Set attributevalues) {
       this.name = name;
       this.attributevalues = attributevalues;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getAttributevalues() {
        return this.attributevalues;
    }
    
    public void setAttributevalues(Set attributevalues) {
        this.attributevalues = attributevalues;
    }




}


