package Strore.entity;
// Generated Aug 25, 2019 7:33:18 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Blog generated by hbm2java
 */
public class Blog  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String title;
     private String description;
     private String content;
     private String thumbnail;
     private String image;
     private Date createdDate;
     private Date publishedDate;
     private boolean status;
     private Date onDate;
     private Date offDate;
     private int odering;
     private String nameOfWriter;
     private Set commentses = new HashSet(0);

    public Blog() {
    }

	
    public Blog(User user, String title, String description, String content, String thumbnail, String image, Date createdDate, Date publishedDate, boolean status, Date onDate, Date offDate, int odering, String nameOfWriter) {
        this.user = user;
        this.title = title;
        this.description = description;
        this.content = content;
        this.thumbnail = thumbnail;
        this.image = image;
        this.createdDate = createdDate;
        this.publishedDate = publishedDate;
        this.status = status;
        this.onDate = onDate;
        this.offDate = offDate;
        this.odering = odering;
        this.nameOfWriter = nameOfWriter;
    }
    public Blog(User user, String title, String description, String content, String thumbnail, String image, Date createdDate, Date publishedDate, boolean status, Date onDate, Date offDate, int odering, String nameOfWriter, Set commentses) {
       this.user = user;
       this.title = title;
       this.description = description;
       this.content = content;
       this.thumbnail = thumbnail;
       this.image = image;
       this.createdDate = createdDate;
       this.publishedDate = publishedDate;
       this.status = status;
       this.onDate = onDate;
       this.offDate = offDate;
       this.odering = odering;
       this.nameOfWriter = nameOfWriter;
       this.commentses = commentses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getThumbnail() {
        return this.thumbnail;
    }
    
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getPublishedDate() {
        return this.publishedDate;
    }
    
    public void setPublishedDate(Date publishedDate) {
        this.publishedDate = publishedDate;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Date getOnDate() {
        return this.onDate;
    }
    
    public void setOnDate(Date onDate) {
        this.onDate = onDate;
    }
    public Date getOffDate() {
        return this.offDate;
    }
    
    public void setOffDate(Date offDate) {
        this.offDate = offDate;
    }
    public int getOdering() {
        return this.odering;
    }
    
    public void setOdering(int odering) {
        this.odering = odering;
    }
    public String getNameOfWriter() {
        return this.nameOfWriter;
    }
    
    public void setNameOfWriter(String nameOfWriter) {
        this.nameOfWriter = nameOfWriter;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }




}


