package Strore.entity;
// Generated Aug 25, 2019 7:33:18 AM by Hibernate Tools 4.3.1



/**
 * OrderdetailId generated by hbm2java
 */
public class OrderdetailId  implements java.io.Serializable {


     private int productsId;
     private int orderId;

    public OrderdetailId() {
    }

    public OrderdetailId(int productsId, int orderId) {
       this.productsId = productsId;
       this.orderId = orderId;
    }
   
    public int getProductsId() {
        return this.productsId;
    }
    
    public void setProductsId(int productsId) {
        this.productsId = productsId;
    }
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderdetailId) ) return false;
		 OrderdetailId castOther = ( OrderdetailId ) other; 
         
		 return (this.getProductsId()==castOther.getProductsId())
 && (this.getOrderId()==castOther.getOrderId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProductsId();
         result = 37 * result + this.getOrderId();
         return result;
   }   


}


