package Strore.entity;
// Generated Aug 25, 2019 7:33:18 AM by Hibernate Tools 4.3.1



/**
 * Orderdetail generated by hbm2java
 */
public class Orderdetail  implements java.io.Serializable {


     private OrderdetailId id;
     private Order order;
     private Products products;
     private String total;
     private String quantity;
     private float amount;
     private String status;

    public Orderdetail() {
    }

    public Orderdetail(OrderdetailId id, Order order, Products products, String total, String quantity, float amount, String status) {
       this.id = id;
       this.order = order;
       this.products = products;
       this.total = total;
       this.quantity = quantity;
       this.amount = amount;
       this.status = status;
    }
   
    public OrderdetailId getId() {
        return this.id;
    }
    
    public void setId(OrderdetailId id) {
        this.id = id;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }
    public float getAmount() {
        return this.amount;
    }
    
    public void setAmount(float amount) {
        this.amount = amount;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


