package Strore.entity;
// Generated Aug 25, 2019 7:33:18 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer id;
     private Brand brand;
     private Category category;
     private String codeId;
     private String name;
     private Date dateCreated;
     private float price;
     private boolean status;
     private int quatity;
     private int viewCount;
     private String hotSale;
     private String image;
     private String description;
     private String imageList;
     private String warranty;
     private String productscol;
     private int voteOfStar;
     private Set commentses = new HashSet(0);
     private Set attributevalues = new HashSet(0);
     private Set orderdetails = new HashSet(0);
     private Set users = new HashSet(0);

    public Products() {
    }

	
    public Products(Brand brand, Category category, String codeId, String name, Date dateCreated, float price, boolean status, int quatity, int viewCount, String hotSale, String image, String description, String imageList, String warranty, String productscol, int voteOfStar) {
        this.brand = brand;
        this.category = category;
        this.codeId = codeId;
        this.name = name;
        this.dateCreated = dateCreated;
        this.price = price;
        this.status = status;
        this.quatity = quatity;
        this.viewCount = viewCount;
        this.hotSale = hotSale;
        this.image = image;
        this.description = description;
        this.imageList = imageList;
        this.warranty = warranty;
        this.productscol = productscol;
        this.voteOfStar = voteOfStar;
    }
    public Products(Brand brand, Category category, String codeId, String name, Date dateCreated, float price, boolean status, int quatity, int viewCount, String hotSale, String image, String description, String imageList, String warranty, String productscol, int voteOfStar, Set commentses, Set attributevalues, Set orderdetails, Set users) {
       this.brand = brand;
       this.category = category;
       this.codeId = codeId;
       this.name = name;
       this.dateCreated = dateCreated;
       this.price = price;
       this.status = status;
       this.quatity = quatity;
       this.viewCount = viewCount;
       this.hotSale = hotSale;
       this.image = image;
       this.description = description;
       this.imageList = imageList;
       this.warranty = warranty;
       this.productscol = productscol;
       this.voteOfStar = voteOfStar;
       this.commentses = commentses;
       this.attributevalues = attributevalues;
       this.orderdetails = orderdetails;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getCodeId() {
        return this.codeId;
    }
    
    public void setCodeId(String codeId) {
        this.codeId = codeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public int getQuatity() {
        return this.quatity;
    }
    
    public void setQuatity(int quatity) {
        this.quatity = quatity;
    }
    public int getViewCount() {
        return this.viewCount;
    }
    
    public void setViewCount(int viewCount) {
        this.viewCount = viewCount;
    }
    public String getHotSale() {
        return this.hotSale;
    }
    
    public void setHotSale(String hotSale) {
        this.hotSale = hotSale;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImageList() {
        return this.imageList;
    }
    
    public void setImageList(String imageList) {
        this.imageList = imageList;
    }
    public String getWarranty() {
        return this.warranty;
    }
    
    public void setWarranty(String warranty) {
        this.warranty = warranty;
    }
    public String getProductscol() {
        return this.productscol;
    }
    
    public void setProductscol(String productscol) {
        this.productscol = productscol;
    }
    public int getVoteOfStar() {
        return this.voteOfStar;
    }
    
    public void setVoteOfStar(int voteOfStar) {
        this.voteOfStar = voteOfStar;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }
    public Set getAttributevalues() {
        return this.attributevalues;
    }
    
    public void setAttributevalues(Set attributevalues) {
        this.attributevalues = attributevalues;
    }
    public Set getOrderdetails() {
        return this.orderdetails;
    }
    
    public void setOrderdetails(Set orderdetails) {
        this.orderdetails = orderdetails;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


