package Strore.entity;
// Generated Aug 25, 2019 7:33:18 AM by Hibernate Tools 4.3.1



/**
 * Slides generated by hbm2java
 */
public class Slides  implements java.io.Serializable {


     private Integer id;
     private String title1;
     private String title2;
     private String title3;
     private String content1;
     private String content2;
     private String url;
     private String nameOfButton;
     private boolean status;

    public Slides() {
    }

    public Slides(String title1, String title2, String title3, String content1, String content2, String url, String nameOfButton, boolean status) {
       this.title1 = title1;
       this.title2 = title2;
       this.title3 = title3;
       this.content1 = content1;
       this.content2 = content2;
       this.url = url;
       this.nameOfButton = nameOfButton;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle1() {
        return this.title1;
    }
    
    public void setTitle1(String title1) {
        this.title1 = title1;
    }
    public String getTitle2() {
        return this.title2;
    }
    
    public void setTitle2(String title2) {
        this.title2 = title2;
    }
    public String getTitle3() {
        return this.title3;
    }
    
    public void setTitle3(String title3) {
        this.title3 = title3;
    }
    public String getContent1() {
        return this.content1;
    }
    
    public void setContent1(String content1) {
        this.content1 = content1;
    }
    public String getContent2() {
        return this.content2;
    }
    
    public void setContent2(String content2) {
        this.content2 = content2;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getNameOfButton() {
        return this.nameOfButton;
    }
    
    public void setNameOfButton(String nameOfButton) {
        this.nameOfButton = nameOfButton;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


